version: '3.7'

networks:
  elasticsearch-7.16.1-network:
    name: elasticsearch-7.16.1-network
    driver: bridge

volumes:
  elasticsearch-7.16.1__data:
    driver: local

services:
  elasticsearch-7.16.1:
    container_name: elasticsearch-7.16.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    networks:
      - elasticsearch-7.16.1-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: elasticsearch-7.16.1__data
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: false
    ports:
      - 9200:9200
      - 5601:5601
    env_file:
      - ./docker-compose.env

  kibana-7.16.1:
    container_name: kibana-7.16.1
    image: docker.elastic.co/kibana/kibana:7.16.1
    network_mode: service:elasticsearch-7.16.1
    env_file:
      - ./kibana.env
