version: "3.7"

services:
  imgproxy-latest:
    container_name: imgproxy-latest
    image: darthsim/imgproxy:latest
    network_mode: "bridge"
    env_file:
      - ./docker-compose.env
    ports:
      - "8100:8100"
